# This is a basic workflow to help you get started with Actions

name: GEN-

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: '3.9' # optional, default is 3.x
      
      - uses: actions/cache@v2
        id: cache-webscraper
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-webscraper
          
      - name: Install deps
        if: steps.cache-webscraper.outputs.cache-hit != 'true'
        run: python -m pip install html5lib requests BeautifulSoup4

      - name: Make tree
        run: |
          cd webscraper
          python webscraper.py
      
      - name: Delete prev version
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release new version
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          prerelease: false
          commitish: ${{ github.sha }}
          gzip: false
          allow_override: true
          files: |
            vub-data-tree.json:./data_tree_dummy.json
          body: |
            Current latest version
            
            Download via [Hippo](https://github.com/OsamaBinNaughty-hub/Hippo2.0)
